"""
Builds every generated file of the ASG CAD Master Standard package from the
definitions in asg_standard.py. Idempotent: re-running rebuilds the same
files; nothing outside ASG_CAD_MASTER_STANDARD/ is touched.

    python build_all.py && python qa_validate.py
"""

import csv
from pathlib import Path

from ezdxf.math import Vec2

import asg_standard as S

ROOT = Path(__file__).resolve().parent.parent
D_MASTER = ROOT / "01_Master_Template"
D_TEMPL = ROOT / "02_Drawing_Templates"
D_PSETUP = ROOT / "03_Page_Setups"
D_PLOT = ROOT / "04_Plotting_Standards"
D_QA = ROOT / "07_QA_Validation"

MASTER_DXF = D_MASTER / "ASG_Master_Template.dxf"
SETUP_LSP = D_MASTER / "ASG_Setup.lsp"
QA_DXF = D_QA / "QA_TEST_DRAWING_temporary.dxf"


def build_master():
    S.save_dxf(S.new_document(), MASTER_DXF)


def build_size_templates():
    for sheet in S.SHEETS:
        S.save_dxf(S.new_document(sheets=[sheet]), D_TEMPL / f"ASG_{sheet[0]}.dxf")


def build_page_setup_register():
    D_PSETUP.mkdir(parents=True, exist_ok=True)
    with open(D_PSETUP / "ASG_Page_Setups.csv", "w", newline="", encoding="utf-8") as f:
        wr = csv.writer(f)
        wr.writerow(["Named page setup", "Layout", "Plot device", "Paper (canonical media name)",
                     "Paper size mm", "Orientation", "Plot area", "Plot scale", "Plot offset",
                     "Plot style table", "Plot object lineweights", "Scale lineweights",
                     "Title block", "Default viewport"])
        for name, w, h, paper, tb, vps in S.SHEETS:
            wr.writerow([f"ASG-{name}", name, S.PLOTTER, S.media_name(paper, w, h), f"{w:.0f} x {h:.0f}",
                         "Landscape" if w > h else "Portrait", "Layout", "1:1 (mm = units)", "0,0",
                         S.CTB_NAME, "Yes", "No", tb, f"1:{vps}, display locked, layer ASG-VIEWPORT"])


def build_ctb():
    S.build_ctb(D_PLOT / S.CTB_NAME)


# ---------------------------------------------------------------------------
# AutoLISP: generated from the same definitions (setup + in-AutoCAD QA)
# ---------------------------------------------------------------------------
def _s(v):
    return '"' + str(v).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _b(v):
    return "T" if v else "nil"


def _atom(v):
    return _s(v) if isinstance(v, str) else (repr(float(v)) if isinstance(v, float) else str(v))


LISP_HEAD = r''';;; ASG_Setup.lsp  -  ASG CAD Master Standard {rev}
;;; Saeed Al Siraj Glass & Aluminium Works L.L.C.  |  Al Siraj Group
;;;
;;; GENERATED by 08_Automation_Source/build_all.py from asg_standard.py.
;;; Do not edit by hand - change asg_standard.py and rebuild.
;;;
;;; Commands (all idempotent - re-running updates, never duplicates):
;;;   ASG-SETUP        table styles + named page setups + drawing variables,
;;;                    then ASG-QA.  Run once in ASG_Master_Template before
;;;                    SAVEAS DWG / DWT.
;;;   ASG-QA           read-only check of the whole standard inside AutoCAD;
;;;                    prints PASS / FAIL lines and writes ASG_QA_Log.txt
;;;                    next to the drawing.
;;;   ASG-PROFILE      OPTIONAL: user-profile (registry) settings. Asks first.
;;;
;;; Status: written without access to AutoCAD - ASG-QA is the verification.

(vl-load-com)

(defun asg:doc () (vla-get-ActiveDocument (vlax-get-acad-object)))

(defun asg:item (coll name / r)
  (setq r (vl-catch-all-apply 'vla-Item (list coll name)))
  (if (vl-catch-all-error-p r) nil r))

(defun asg:color (aci / c)
  (setq c (vla-GetInterfaceObject (vlax-get-acad-object)
            (strcat "AutoCAD.AcCmColor." (substr (getvar "ACADVER") 1 2))))
  (vla-put-ColorIndex c aci)
  c)

;; ---------------------------------------------------------------- tables
;; row types: 1 data, 2 title, 4 header | align: 1 TL, 4 ML, 5 MC
(defun asg:ts (name desc tH tA hH hA dH dA tSup hSup / dict ts)
  (setq dict (vla-Item (vla-get-Dictionaries (asg:doc)) "ACAD_TABLESTYLE"))
  (or (setq ts (asg:item dict name))
      (setq ts (vla-AddObject dict name "AcDbTableStyle")))
  (vla-put-Description ts desc)
  (vla-put-FlowDirection ts 0)
  (vla-put-HorzCellMargin ts 1.5)
  (vla-put-VertCellMargin ts 1.0)
  (vla-put-TitleSuppressed ts (if tSup :vlax-true :vlax-false))
  (vla-put-HeaderSuppressed ts (if hSup :vlax-true :vlax-false))
  (vla-SetTextStyle ts 7 "ASG-TEXT-SHEET")
  (vla-SetTextHeight ts 2 tH) (vla-SetAlignment ts 2 tA)
  (vla-SetTextHeight ts 4 hH) (vla-SetAlignment ts 4 hA)
  (vla-SetTextHeight ts 1 dH) (vla-SetAlignment ts 1 dA)
  (vla-SetColor ts 7 (asg:color 0))               ; ByBlock
  (vla-SetBackgroundColorNone ts 3 :vlax-true)    ; title + data: no fill
  (vla-SetBackgroundColorNone ts 4 :vlax-false)
  (vla-SetBackgroundColor ts 4 (asg:color 254))   ; header: light grey
  (vla-SetGridLineWeight ts 18 7 18)              ; inside grid 0.18
  (vla-SetGridLineWeight ts 45 7 35)              ; outline 0.35
  (princ (strcat "\n  table style " name " ok"))
  ts)

;; ---------------------------------------------------------- page setups
(defun asg:pagesetups (/ pcs name pc)
  (setq pcs (vla-get-PlotConfigurations (asg:doc)))
  (vlax-for lay (vla-get-Layouts (asg:doc))
    (if (= (vla-get-ModelType lay) :vlax-false)
      (progn
        (setq name (strcat "ASG-" (vla-get-Name lay)))
        (or (setq pc (asg:item pcs name))
            (setq pc (vla-Add pcs name :vlax-false)))
        (vla-CopyFrom pc lay)
        (princ (strcat "\n  page setup " name " ok"))))))

;; ------------------------------------------------------------------ QA
(setq asg:pass 0 asg:fail 0 asg:lines nil)
(defun asg:out (s) (princ (strcat "\n" s)) (setq asg:lines (cons s asg:lines)))
(defun asg:chk (label ok)
  (if ok (setq asg:pass (1+ asg:pass)) (setq asg:fail (1+ asg:fail)))
  (asg:out (strcat (if ok "PASS  " "FAIL  ") label))
  ok)
(defun asg:same (a b)
  (cond ((and (numberp a) (numberp b)) (equal (float a) (float b) 1e-6))
        ((and (= (type a) 'STR) (= (type b) 'STR)) (= (strcase a) (strcase b)))
        (T (equal a b))))
(defun asg:var (name val)
  (asg:chk (strcat "variable " name " = " (vl-princ-to-string val)) (asg:same (getvar name) val)))
(defun asg:dv (e code def / a) (if (setq a (assoc code e)) (cdr a) def))
(defun asg:anno (ename) (and (assoc -3 (entget ename '("AcadAnnotative"))) T))
(defun asg:uniq (l / r) (foreach x l (if (not (member x r)) (setq r (cons x r)))) r)

(defun asg:layer (name aci lt lw plot / o e)
  (if (setq o (tblobjname "LAYER" name))
    (progn
      (setq e (entget o))
      (asg:chk (strcat "layer " name)
        (and (= (abs (cdr (assoc 62 e))) aci)
             (asg:same (cdr (assoc 6 e)) lt)
             (= (asg:dv e 370 -3) lw)
             (= (asg:dv e 290 1) plot))))
    (asg:chk (strcat "layer " name " - MISSING") nil)))

(defun asg:tstyle (name font anno / o e)
  (if (setq o (tblobjname "STYLE" name))
    (progn
      (setq e (entget o))
      (asg:chk (strcat "text style " name)
        (and (asg:same (cdr (assoc 3 e)) font)
             (equal (cdr (assoc 40 e)) 0.0 1e-9)
             (eq (asg:anno o) anno))))
    (asg:chk (strcat "text style " name " - MISSING") nil)))

(defun asg:dstyle (name dec adec anno / o e)
  (if (setq o (tblobjname "DIMSTYLE" name))
    (progn
      (setq e (entget o))
      (asg:chk (strcat "dimension style " name)
        (and (= (asg:dv e 271 4) dec)                 ; DIMDEC
             (= (asg:dv e 179 0) adec)                ; DIMADEC
             (equal (asg:dv e 140 0.18) 2.5 1e-9)     ; DIMTXT
             (equal (asg:dv e 41 0.18) 2.5 1e-9)      ; DIMASZ
             (equal (asg:dv e 144 1.0) 1.0 1e-9)      ; DIMLFAC - true measurement
             (eq (asg:anno o) anno))))
    (asg:chk (strcat "dimension style " name " - MISSING") nil)))

(defun asg:mlstyle (name anno / d e)
  (setq d (cdr (assoc -1 (dictsearch (namedobjdict) "ACAD_MLEADERSTYLE"))))
  (if (setq e (dictsearch d name))
    (asg:chk (strcat "multileader style " name " (annotative " (if anno "yes" "no") ")")
             (= (asg:dv e 296 0) (if anno 1 0)))
    (asg:chk (strcat "multileader style " name " - MISSING") nil)))

(defun asg:tblstyle (name / d)
  (setq d (cdr (assoc -1 (dictsearch (namedobjdict) "ACAD_TABLESTYLE"))))
  (asg:chk (strcat "table style " name) (and d (dictsearch d name))))

(defun asg:scales (want / names)
  (foreach p (dictsearch (namedobjdict) "ACAD_SCALELIST")
    (if (= (car p) 350) (setq names (cons (cdr (assoc 300 (entget (cdr p)))) names))))
  (foreach s want (asg:chk (strcat "annotation scale " s) (member s names)))
  (asg:chk (strcat "annotation scale list: " (itoa (length names)) " entries, no duplicates")
           (= (length names) (length (asg:uniq names)))))

(defun asg:layout (name media ctb / lay names num den std)
  (if (setq lay (asg:item (vla-get-Layouts (asg:doc)) name))
    (progn
      (vla-RefreshPlotDeviceInfo lay)
      (asg:chk (strcat name ": plot device DWG To PDF.pc3")
               (asg:same (vla-get-ConfigName lay) "DWG To PDF.pc3"))
      (setq names (vl-catch-all-apply
                    '(lambda () (vlax-safearray->list (vlax-variant-value (vla-GetCanonicalMediaNames lay))))))
      (asg:chk (strcat name ": paper " media " exists on device and is selected")
               (and (listp names) (member media names) (= (vla-get-CanonicalMediaName lay) media)))
      (asg:chk (strcat name ": plot area = Layout") (= (vla-get-PlotType lay) 5))
      (vla-GetCustomScale lay 'num 'den)
      (setq std (and (= (vla-get-UseStandardScale lay) :vlax-true) (= (vla-get-StandardScale lay) 16)))
      (asg:chk (strcat name ": plot scale 1:1") (or std (and den (/= den 0) (equal (/ num den) 1.0 1e-9))))
      (asg:chk (strcat name ": plot style table " ctb) (asg:same (vla-get-StyleSheet lay) ctb))
      (setq names (vl-catch-all-apply
                    '(lambda () (vlax-safearray->list (vlax-variant-value (vla-GetPlotStyleTableNames lay))))))
      (asg:chk (strcat name ": " ctb " installed in Plot Styles folder")
               (and (listp names) (vl-some '(lambda (x) (asg:same x ctb)) names)))
      (asg:chk (strcat name ": plot object lineweights on, not scaled")
               (and (= (vla-get-PlotWithLineweights lay) :vlax-true)
                    (= (vla-get-ScaleLineweights lay) :vlax-false)))
      (asg:chk (strcat name ": viewport borders not plotted")
               (= (vla-get-PlotViewportBorders lay) :vlax-false)))
    (asg:chk (strcat "layout " name " - MISSING") nil)))

(defun asg:tbattrs (blk tags / e found)
  (if (setq e (tblobjname "BLOCK" blk))
    (progn
      (while (setq e (entnext e))
        (if (= (cdr (assoc 0 (entget e))) "ATTDEF")
          (setq found (cons (strcase (cdr (assoc 2 (entget e)))) found))))
      (asg:chk (strcat "title block " blk ": " (itoa (length tags)) " attributes")
               (and (= (length found) (length tags))
                    (vl-every '(lambda (tg) (member tg found)) tags))))
    (asg:chk (strcat "title block " blk " - MISSING") nil)))

(defun asg:noxrefs (/ b ok)
  (setq ok T b (tblnext "BLOCK" T))
  (while b
    (if (= 4 (logand 4 (cdr (assoc 70 b)))) (setq ok nil))
    (setq b (tblnext "BLOCK")))
  (asg:chk "no external references" ok))

(defun asg:writelog (/ fn f)
  (setq fn (strcat (getvar "DWGPREFIX") "ASG_QA_Log.txt"))
  (if (setq f (open fn "w"))
    (progn
      (foreach l (reverse asg:lines) (write-line l f))
      (close f)
      (princ (strcat "\nQA log written: " fn)))
    (princ "\nQA log could not be written (folder read-only).")))
'''

LISP_TAIL = r'''
(defun c:ASG-SETUP ()
  (princ "\nASG-SETUP ---------------------------------------------")
  (asg:tablestyles)
  (asg:pagesetups)
  (asg:setvars)
  (c:ASG-QA)
  (princ "\nASG-SETUP complete. If FAIL = 0: SAVEAS DWG, then SAVEAS DWT.")
  (princ))

(princ "\nASG_Setup loaded: ASG-SETUP, ASG-QA, ASG-PROFILE (optional).")
(princ)
'''


def build_lisp():
    L = [LISP_HEAD.replace("{rev}", S.STANDARD_REV)]
    # table styles
    L.append("(defun asg:tablestyles ()")
    for name, t, h, d, ts, hs, use in S.TABLE_STYLES:
        L.append(f"  (asg:ts {_s(name)} {_s(use)} {t[0]} {S.TABLE_ALIGN_CODE[t[1]]} "
                 f"{h[0]} {S.TABLE_ALIGN_CODE[h[1]]} {d[0]} {S.TABLE_ALIGN_CODE[d[1]]} {_b(ts)} {_b(hs)})")
    L.append("  (princ))\n")
    # drawing variables
    L.append("(defun asg:setvars (/ r)")
    L.append("  (foreach p '(" + " ".join(f"({_s(v)} . {_atom(x)})" for v, x, _p in S.SETUP_DRAWING_VARS) + ")")
    L.append("    (setq r (vl-catch-all-apply 'setvar (list (car p) (cdr p))))")
    L.append('    (princ (strcat "\\n  " (car p) (if (vl-catch-all-error-p r) " NOT SET (not supported in this release)" " set"))))')
    L.append("  (princ))\n")
    # QA
    L.append("(defun c:ASG-QA ()")
    L.append("  (setq asg:pass 0 asg:fail 0 asg:lines nil)")
    L.append(f'  (asg:out "ASG-QA  -  ASG CAD Master Standard {S.STANDARD_REV}  -  read-only check")')
    L.append('  (asg:out (strcat "Drawing: " (getvar "DWGPREFIX") (getvar "DWGNAME")))')
    L.append("  ;; units and drawing variables")
    for var, val, _p in S.HEADER_VARS:
        if isinstance(val, tuple) or var in ("$UCSXDIR", "$UCSYDIR", "$UCSORG"):
            continue
        if var == "$CECOLOR":  # getvar returns a string for CECOLOR
            val = {256: "BYLAYER", 0: "BYBLOCK"}[val]
        L.append(f"  (asg:var {_s(var[1:])} {_atom(val)})")
    for var, val, _p in S.HEADER_STYLE_VARS:
        L.append(f"  (asg:var {_s(var[1:])} {_atom(val)})")
    for var, val, _p in S.SETUP_DRAWING_VARS:
        L.append(f"  (asg:var {_s(var)} {_atom(val)})")
    dv = S.dim_values("ASG-DIM-ANNO")
    L.append("  ;; current dimension variables = ASG-DIM-ANNO (no style overrides)")
    for k in ("dimtxsty", "dimtxt", "dimasz", "dimdec", "dimexo", "dimexe", "dimgap", "dimtad", "dimlfac"):
        L.append(f"  (asg:var {_s(k.upper())} {_atom(dv[k])})")
    L.append("  ;; linetypes")
    for name in S.LINETYPES:
        L.append(f'  (asg:chk "linetype {name} loaded" (tblsearch "LTYPE" {_s(name)}))')
    L.append("  ;; layers: colour, linetype, lineweight, plot flag")
    for _c, name, _g, aci, lt, lw, plot, _d, _u in S.LAYERS:
        L.append(f"  (asg:layer {_s(name)} {aci} {_s(lt)} {int(round(lw * 100))} {int(plot)})")
    L.append("  ;; styles")
    for name, ttf, _b2, anno, _u in S.TEXT_STYLES:
        L.append(f"  (asg:tstyle {_s(name)} {_s(ttf)} {_b(anno)})")
    for name, anno, over, _u in S.DIM_STYLES:
        v = dict(S.DIM_BASE, **over)
        L.append(f"  (asg:dstyle {_s(name)} {v['dimdec']} {v['dimadec']} {_b(anno)})")
    for name, anno, *_r in S.MLEADER_STYLES:
        L.append(f"  (asg:mlstyle {_s(name)} {_b(anno)})")
    for name, *_r in S.TABLE_STYLES:
        L.append(f"  (asg:tblstyle {_s(name)})")
    L.append('  (asg:chk "multiline style ASG-MLINE-2" (dictsearch (cdr (assoc -1 (dictsearch (namedobjdict) "ACAD_MLINESTYLE"))) "ASG-MLINE-2"))')
    L.append("  (asg:scales '(" + " ".join(_s(f"1:{s}") for s in S.ANNO_SCALES) + "))")
    L.append("  ;; layouts and page setups")
    for name, w, h, paper, tb, vps in S.SHEETS:
        L.append(f"  (asg:layout {_s(name)} {_s(S.media_name(paper, w, h))} {_s(S.CTB_NAME)})")
        L.append(f'  (asg:chk "named page setup ASG-{name}" (asg:item (vla-get-PlotConfigurations (asg:doc)) "ASG-{name}"))')
    L.append("  ;; title blocks")
    tags = " ".join(_s(t) for t, _p, _d in S.TB_ATTRIBUTES)
    for tb in S.TB_SPECS:
        L.append(f"  (asg:tbattrs {_s(tb)} '({tags}))")
    L.append("  ;; content")
    L.append('  (asg:chk "model space is empty" (null (ssget "_X" (list (cons 410 "Model")))))')
    L.append("  (asg:noxrefs)")
    L.append('  (asg:out (strcat "RESULT: " (itoa asg:pass) " PASS, " (itoa asg:fail) " FAIL"))')
    L.append("  (asg:writelog)")
    L.append("  (princ))\n")
    # profile (opt-in)
    L.append("(defun c:ASG-PROFILE (/ r)")
    L.append('  (initget "Yes No")')
    L.append('  (if (= (getkword "\\nChange YOUR AutoCAD profile (registry) settings to ASG defaults? [Yes/No] <No>: ") "Yes")')
    L.append("    (progn")
    L.append("      (foreach p '(" + " ".join(f"({_s(v)} . {_atom(x)})" for v, x, _p in S.PROFILE_VARS) + ")")
    L.append("        (setq r (vl-catch-all-apply 'setvar (list (car p) (cdr p))))")
    L.append('        (princ (strcat "\\n  " (car p) (if (vl-catch-all-error-p r) " not set" " set"))))')
    L.append('      (princ "\\nASG profile settings applied."))')
    L.append('    (princ "\\nNo changes made."))')
    L.append("  (princ))")
    L.append(LISP_TAIL)
    text = "\n".join(L)
    _check_parens(text)
    SETUP_LSP.parent.mkdir(parents=True, exist_ok=True)
    SETUP_LSP.write_text(text.replace("\n", "\r\n"), encoding="ascii")


def _check_parens(text):
    """Structural check of the generated LISP: balanced parentheses outside
    strings and comments, every top-level form closed."""
    depth, in_str, esc, comment = 0, False, False, False
    for ch in text:
        if comment:
            comment = ch != "\n"
            continue
        if in_str:
            if esc:
                esc = False
            elif ch == "\\":
                esc = True
            elif ch == '"':
                in_str = False
            continue
        if ch == ";":
            comment = True
        elif ch == '"':
            in_str = True
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth < 0:
                raise ValueError("ASG_Setup.lsp: unbalanced ')'")
    if depth or in_str:
        raise ValueError(f"ASG_Setup.lsp: unbalanced, depth {depth}, open string {in_str}")


# ---------------------------------------------------------------------------
# Temporary QA drawing - SEPARATE from the master (never a template)
# ---------------------------------------------------------------------------
QA_LW_Y0 = 250.0  # paper y of first lineweight sample
QA_LW_STEP = 9.0
QA_LW_X = (230.0, 300.0)
QA_VIEWPORTS = (((25, 15, 125, 282), 20, (450, 1100)),
                ((130, 15, 225, 140), 5, (5120, 120)))


def build_qa_drawing():
    a3 = [s for s in S.SHEETS if s[0] == "A3-LANDSCAPE"]
    doc = S.new_document(sheets=a3)
    msp = doc.modelspace()
    # 1:20 test geometry - a 1200 x 2400 opening
    msp.add_lwpolyline([(0, 0), (1200, 0), (1200, 2400), (0, 2400)], close=True,
                       dxfattribs={"layer": "ASG-OUTLINE-PRIMARY"})
    for p1, p2, base, ang in (((0, 0), (1200, 0), (0, -300), 0), ((0, 0), (0, 2400), (-300, 0), 90)):
        msp.add_linear_dim(base=base, p1=p1, p2=p2, angle=ang, dimstyle="ASG-DIM-FIXED",
                           override={"dimscale": 20}, dxfattribs={"layer": "ASG-DIMENSION"}).render()
    t = msp.add_text("TEXT 2.5 @1:20", height=2.5 * 20,
                     dxfattribs={"style": "ASG-TEXT-NOTE", "layer": "ASG-TEXT-NOTE"})
    t.set_placement((0, 2550))
    # 1:5 detail geometry at x = 5000
    ox = 5000
    sq = [(ox, 0), (ox + 50, 0), (ox + 50, 100), (ox, 100)]
    msp.add_lwpolyline(sq, close=True, dxfattribs={"layer": "ASG-SECTION-CUT"})
    hatch = msp.add_hatch(dxfattribs={"layer": "ASG-HATCH-FILL"})
    hatch.set_solid_fill(color=256)
    hatch.paths.add_polyline_path(sq, is_closed=True)
    msp.add_linear_dim(base=(ox, -25), p1=(ox, 0), p2=(ox + 50, 0), dimstyle="ASG-DIM-DETAIL",
                       override={"dimscale": 5}, dxfattribs={"layer": "ASG-DIMENSION"}).render()
    c = Vec2(ox + 150, 0)
    msp.add_line(c, c + Vec2(120, 0), dxfattribs={"layer": "ASG-OUTLINE-SECONDARY"})
    msp.add_line(c, c + Vec2.from_deg_angle(30, 120), dxfattribs={"layer": "ASG-OUTLINE-SECONDARY"})
    msp.add_angular_dim_cra(center=c, radius=90, start_angle=0, end_angle=30, distance=0,
                            dimstyle="ASG-DIM-ANGULAR", override={"dimscale": 5},
                            dxfattribs={"layer": "ASG-DIMENSION"}).render()
    cc = (ox + 100, 200)
    msp.add_circle(cc, 40, dxfattribs={"layer": "ASG-OUTLINE-SECONDARY"})
    msp.add_radius_dim(center=cc, radius=40, angle=45, dimstyle="ASG-DIM-RADIUS",
                       override={"dimscale": 5}, dxfattribs={"layer": "ASG-DIMENSION"}).render()
    msp.add_diameter_dim(center=cc, radius=40, angle=200, dimstyle="ASG-DIM-DIAMETER",
                         override={"dimscale": 5}, dxfattribs={"layer": "ASG-DIMENSION"}).render()
    # objects that must NOT appear on a plot
    msp.add_line((0, 0), (1200, 2400), dxfattribs={"layer": "ASG-CONSTRUCTION"})
    msp.add_text("NOPLOT", height=100, dxfattribs={"layer": "ASG-NOPLOT"}).set_placement((300, 1200))

    lay = doc.layouts.get("A3-LANDSCAPE")
    for e in list(lay):
        if e.dxftype() == "VIEWPORT" and e.dxf.id != 1:
            lay.delete_entity(e)
    for (x1, y1, x2, y2), scale, ctr in QA_VIEWPORTS:
        vp = lay.add_viewport(center=((x1 + x2) / 2, (y1 + y2) / 2), size=(x2 - x1, y2 - y1),
                              view_center_point=ctr, view_height=(y2 - y1) * scale,
                              dxfattribs={"layer": "ASG-VIEWPORT"})
        vp.dxf.flags |= 16384
    x1, x2 = QA_LW_X
    for i, (lw, cls, _u) in enumerate(S.LW_MATRIX):
        y = QA_LW_Y0 - i * QA_LW_STEP
        layer = next(l[1] for l in S.LAYERS if l[5] == lw and l[6])
        lay.add_line((x1, y), (x2, y), dxfattribs={"layer": layer})
        S._text(lay, f"{lw:.2f} {cls} - {layer}", x2 + 3, y - 1, 1.8, "ASG-TEXT-SHEET", "ASG-TEXT")
    y = 175
    for use, h, style in S.TEXT_HEIGHTS:
        y -= h + 2.5
        S._text(lay, f"{h} mm {use}", 230, y, h, style.split(" ")[0], "ASG-TEXT")
    S.save_dxf(doc, QA_DXF)


def main():
    build_master()
    build_size_templates()
    build_page_setup_register()
    build_ctb()
    build_lisp()
    build_qa_drawing()
    for p in sorted(ROOT.rglob("*")):
        if p.is_file() and p.suffix in (".dxf", ".ctb", ".csv", ".lsp"):
            print("written", p.relative_to(ROOT))


if __name__ == "__main__":
    main()
