"""
Builds every generated file of the ASG CAD Master Standard package from the
definitions in asg_standard.py. Idempotent: re-running rebuilds the same
files; nothing outside ASG_CAD_MASTER_STANDARD/ is touched.

    python build_all.py && python qa_validate.py
"""

import csv
from pathlib import Path

from ezdxf.math import Vec2

import asg_standard as S

ROOT = Path(__file__).resolve().parent.parent
D_MASTER = ROOT / "01_Master_Template"
D_TEMPL = ROOT / "02_Drawing_Templates"
D_PSETUP = ROOT / "03_Page_Setups"
D_PLOT = ROOT / "04_Plotting_Standards"
D_QA = ROOT / "07_QA_Validation"

MASTER_DXF = D_MASTER / "ASG_Master_Template.dxf"
SETUP_LSP = D_MASTER / "ASG_Install.lsp"
D_KIT = ROOT / "09_Team_Kit"
QA_DXF = D_QA / "QA_TEST_DRAWING_temporary.dxf"


def build_master():
    S.save_dxf(S.new_document(), MASTER_DXF)


def build_size_templates():
    for sheet in S.SHEETS:
        S.save_dxf(S.new_document(sheets=[sheet]), D_TEMPL / f"ASG_{sheet[0]}.dxf")


def build_page_setup_register():
    D_PSETUP.mkdir(parents=True, exist_ok=True)
    with open(D_PSETUP / "ASG_Page_Setups.csv", "w", newline="", encoding="utf-8") as f:
        wr = csv.writer(f)
        wr.writerow(["Named page setup", "Layout", "Plot device", "Paper (canonical media name)",
                     "Paper size mm", "Orientation", "Plot area", "Plot scale", "Plot offset",
                     "Plot style table", "Plot object lineweights", "Scale lineweights",
                     "Title block", "Default viewport"])
        for name, w, h, paper, tb, vps in S.SHEETS:
            wr.writerow([f"ASG-{name}", name, S.PLOTTER, S.media_name(paper, w, h), f"{w:.0f} x {h:.0f}",
                         "Landscape" if w > h else "Portrait", "Layout", "1:1 (mm = units)", "0,0",
                         S.CTB_NAME, "Yes", "No", tb, f"1:{vps}, display locked, layer ASG-VIEWPORT"])


def build_ctb():
    S.build_ctb(D_PLOT / S.CTB_NAME)


# ---------------------------------------------------------------------------
# AutoLISP: generated from the same definitions (setup + in-AutoCAD QA)
# ---------------------------------------------------------------------------
def _s(v):
    return '"' + str(v).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _b(v):
    return "T" if v else "nil"


def _atom(v):
    return _s(v) if isinstance(v, str) else (repr(float(v)) if isinstance(v, float) else str(v))


LISP_HEAD = r''';;; ASG_Install.lsp  -  ASG CAD Master Standard {rev}
;;; Saeed Al Siraj Glass & Aluminium Works L.L.C.  |  Al Siraj Group
;;;
;;; GENERATED by 08_Automation_Source/build_all.py from asg_standard.py.
;;; Do not edit by hand - change asg_standard.py and rebuild.
;;;
;;; HOW TO USE: drag this file into the AutoCAD window (or APPLOAD > Load).
;;; It installs automatically:
;;;   * with ASG_Master_Template.dxf open  -> builds and installs the template
;;;     (CAD in-charge, once)
;;;   * in any other drawing               -> installs the template from the
;;;     Team Kit (every team member, once per PC)
;;;
;;; Commands available after loading:
;;;   ASG-INSTALL   run the installer again
;;;   ASG-SETUP     table styles + page setups + drawing variables, then ASG-QA
;;;   ASG-QA        read-only check; PASS / FAIL lines + ASG_QA_Log.txt
;;;   ASG-PROFILE   OPTIONAL user-profile settings (asks first)
;;; Every step is protected: a failing step is reported, never aborts the rest.

(vl-load-com)

(defun asg:doc () (vla-get-ActiveDocument (vlax-get-acad-object)))

(defun asg:item (coll name / r)
  (setq r (vl-catch-all-apply 'vla-Item (list coll name)))
  (if (vl-catch-all-error-p r) nil r))

(setq asg:warn 0 asg:wlines nil)
(defun asg:ok (r) (not (vl-catch-all-error-p r)))
(defun asg:warnmsg (label err / s)
  (setq asg:warn (1+ asg:warn)
        s (strcat "WARN  " label " -> " (if err (vl-catch-all-error-message err) "failed"))
        asg:wlines (cons s asg:wlines))
  (princ (strcat "\n  " s)))

;; run (fn . args) protected: returns the result (T for nil results) or nil + WARN
(defun asg:try (label fn args / r)
  (setq r (vl-catch-all-apply fn args))
  (if (vl-catch-all-error-p r)
    (progn (asg:warnmsg label r) nil)
    (if r r T)))

;; AcCmColor: 0 = ByBlock (via ColorMethod), otherwise ACI
(defun asg:color (aci / c)
  (setq c (vl-catch-all-apply 'vla-GetInterfaceObject
            (list (vlax-get-acad-object) (strcat "AutoCAD.AcCmColor." (substr (getvar "ACADVER") 1 2)))))
  (cond ((vl-catch-all-error-p c) nil)
        ((= aci 0) (if (asg:ok (vl-catch-all-apply 'vla-put-ColorMethod (list c 193))) c nil))
        (T (if (asg:ok (vl-catch-all-apply 'vla-put-ColorIndex (list c aci))) c nil))))

;; ---------------------------------------------------------------- tables
;; row types: 1 data, 2 title, 4 header | align: 1 TL, 4 ML, 5 MC
;; Each property: legacy row-type API first, then the cell-style API
;; (AutoCAD 2008+, cell styles _TITLE / _HEADER / _DATA). Failures -> WARN, never abort.
(defun asg:cellstyles (rows / l)
  (if (= 1 (logand rows 1)) (setq l (cons "_DATA" l)))
  (if (= 4 (logand rows 4)) (setq l (cons "_HEADER" l)))
  (if (= 2 (logand rows 2)) (setq l (cons "_TITLE" l)))
  l)

(defun asg:rowprop (ts label fn fn2 rows val / r)
  (setq r (vl-catch-all-apply fn (list ts rows val)))
  (cond ((asg:ok r) T)
        ((and fn2 (vl-every '(lambda (cs) (asg:ok (vl-catch-all-apply fn2 (list ts cs val))))
                            (asg:cellstyles rows)))
         T)
        (T (asg:warnmsg label r) nil)))

(defun asg:gridlw (ts label grid rows lw / r ok)
  (setq r (vl-catch-all-apply 'vla-SetGridLineWeight (list ts grid rows lw)))
  (if (asg:ok r)
    T
    (progn
      (setq ok T)
      (foreach g '(1 2 4 8 16 32)
        (if (= g (logand grid g))
          (if (not (or (asg:ok (vl-catch-all-apply 'vla-SetGridLineWeight (list ts g rows lw)))
                       (vl-every '(lambda (cs) (asg:ok (vl-catch-all-apply 'vla-SetGridLineWeight2 (list ts cs g lw))))
                                 (asg:cellstyles rows))))
            (setq ok nil))))
      (if (not ok) (asg:warnmsg label r))
      ok)))

(defun asg:ts (name desc tH tA hH hA dH dA tSup hSup / dict ts c)
  (setq dict (asg:try "open ACAD_TABLESTYLE dictionary" 'vla-Item
               (list (vla-get-Dictionaries (asg:doc)) "ACAD_TABLESTYLE")))
  (if (= (type dict) 'VLA-OBJECT)
    (or (setq ts (asg:item dict name))
        (setq ts (asg:try (strcat name ": create") 'vla-AddObject (list dict name "AcDbTableStyle")))))
  (if (= (type ts) 'VLA-OBJECT)
    (progn
      (asg:try (strcat name ": description") 'vla-put-Description (list ts desc))
      (asg:try (strcat name ": flow direction") 'vla-put-FlowDirection (list ts 0))
      (asg:try (strcat name ": horizontal cell margin") 'vla-put-HorzCellMargin (list ts 1.5))
      (asg:try (strcat name ": vertical cell margin") 'vla-put-VertCellMargin (list ts 1.0))
      (asg:try (strcat name ": title row on/off") 'vla-put-TitleSuppressed (list ts (if tSup :vlax-true :vlax-false)))
      (asg:try (strcat name ": header row on/off") 'vla-put-HeaderSuppressed (list ts (if hSup :vlax-true :vlax-false)))
      (asg:rowprop ts (strcat name ": text style") 'vla-SetTextStyle 'vla-SetTextStyle2 7 "ASG-TEXT-SHEET")
      (asg:rowprop ts (strcat name ": title height") 'vla-SetTextHeight 'vla-SetTextHeight2 2 tH)
      (asg:rowprop ts (strcat name ": header height") 'vla-SetTextHeight 'vla-SetTextHeight2 4 hH)
      (asg:rowprop ts (strcat name ": data height") 'vla-SetTextHeight 'vla-SetTextHeight2 1 dH)
      (asg:rowprop ts (strcat name ": title alignment") 'vla-SetAlignment 'vla-SetAlignment2 2 tA)
      (asg:rowprop ts (strcat name ": header alignment") 'vla-SetAlignment 'vla-SetAlignment2 4 hA)
      (asg:rowprop ts (strcat name ": data alignment") 'vla-SetAlignment 'vla-SetAlignment2 1 dA)
      (if (setq c (asg:color 0))
        (asg:rowprop ts (strcat name ": text colour ByBlock") 'vla-SetColor 'vla-SetColor2 7 c))
      (asg:rowprop ts (strcat name ": no fill title/data") 'vla-SetBackgroundColorNone nil 3 :vlax-true)
      (asg:rowprop ts (strcat name ": header fill on") 'vla-SetBackgroundColorNone nil 4 :vlax-false)
      (if (setq c (asg:color 254))
        (asg:rowprop ts (strcat name ": header fill grey") 'vla-SetBackgroundColor 'vla-SetBackgroundColor2 4 c))
      (asg:gridlw ts (strcat name ": inside grid 0.18") 18 7 18)
      (asg:gridlw ts (strcat name ": outline 0.35") 45 7 35)
      (princ (strcat "\n  table style " name " done")))
    (princ (strcat "\n  table style " name " NOT created - see WARN above"))))

;; ---------------------------------------------------------- page setups
(defun asg:pagesetups (/ pcs name pc)
  (setq pcs (asg:try "open page setups" 'vla-get-PlotConfigurations (list (asg:doc))))
  (if (= (type pcs) 'VLA-OBJECT)
    (vlax-for lay (vla-get-Layouts (asg:doc))
      (if (= (vla-get-ModelType lay) :vlax-false)
        (progn
          (setq name (strcat "ASG-" (vla-get-Name lay)))
          (or (setq pc (asg:item pcs name))
              (setq pc (asg:try (strcat name ": create") 'vla-Add (list pcs name :vlax-false))))
          (if (and (= (type pc) 'VLA-OBJECT)
                   (asg:try (strcat name ": copy from layout") 'vla-CopyFrom (list pc lay)))
            (princ (strcat "\n  page setup " name " ok"))))))))

;; ------------------------------------------------------------------ QA
(setq asg:pass 0 asg:fail 0 asg:lines nil)
;; Full template = ASG_Master_Template.*; single-size templates and project
;; drawings legitimately miss some layouts / title blocks -> INFO, not FAIL.
(defun asg:master () (wcmatch (strcase (getvar "DWGNAME")) "ASG_MASTER_TEMPLATE*"))
(defun asg:out (s) (princ (strcat "\n" s)) (setq asg:lines (cons s asg:lines)))
(defun asg:chk (label ok)
  (if ok (setq asg:pass (1+ asg:pass)) (setq asg:fail (1+ asg:fail)))
  (asg:out (strcat (if ok "PASS  " "FAIL  ") label))
  ok)
(defun asg:missing (label)
  (if (asg:master)
    (asg:chk (strcat label " - MISSING") nil)
    (asg:out (strcat "INFO  " label " - not in this drawing"))))
(defun asg:same (a b)
  (cond ((and (numberp a) (numberp b)) (equal (float a) (float b) 1e-6))
        ((and (= (type a) 'STR) (= (type b) 'STR)) (= (strcase a) (strcase b)))
        (T (equal a b))))
(defun asg:var (name val)
  (asg:chk (strcat "variable " name " = " (vl-princ-to-string val)) (asg:same (getvar name) val)))
(defun asg:dv (e code def / a) (if (setq a (assoc code e)) (cdr a) def))
(defun asg:anno (ename) (and (assoc -3 (entget ename '("AcadAnnotative"))) T))
(defun asg:uniq (l / r) (foreach x l (if (not (member x r)) (setq r (cons x r)))) r)

(defun asg:layer (name aci lt lw plot / o e)
  (if (setq o (tblobjname "LAYER" name))
    (progn
      (setq e (entget o))
      (asg:chk (strcat "layer " name)
        (and (= (abs (cdr (assoc 62 e))) aci)
             (asg:same (cdr (assoc 6 e)) lt)
             (= (asg:dv e 370 -3) lw)
             (= (asg:dv e 290 1) plot))))
    (asg:chk (strcat "layer " name " - MISSING") nil)))

(defun asg:tstyle (name font anno / o e)
  (if (setq o (tblobjname "STYLE" name))
    (progn
      (setq e (entget o))
      (asg:chk (strcat "text style " name)
        (and (asg:same (cdr (assoc 3 e)) font)
             (equal (cdr (assoc 40 e)) 0.0 1e-9)
             (eq (asg:anno o) anno))))
    (asg:chk (strcat "text style " name " - MISSING") nil)))

(defun asg:dstyle (name dec adec anno / o e)
  (if (setq o (tblobjname "DIMSTYLE" name))
    (progn
      (setq e (entget o))
      (asg:chk (strcat "dimension style " name)
        (and (= (asg:dv e 271 4) dec)                 ; DIMDEC
             (= (asg:dv e 179 0) adec)                ; DIMADEC
             (equal (asg:dv e 140 0.18) 2.5 1e-9)     ; DIMTXT
             (equal (asg:dv e 41 0.18) 2.5 1e-9)      ; DIMASZ
             (equal (asg:dv e 144 1.0) 1.0 1e-9)      ; DIMLFAC - true measurement
             (eq (asg:anno o) anno))))
    (asg:chk (strcat "dimension style " name " - MISSING") nil)))

(defun asg:mlstyle (name anno / d e)
  (setq d (cdr (assoc -1 (dictsearch (namedobjdict) "ACAD_MLEADERSTYLE"))))
  (if (setq e (dictsearch d name))
    (asg:chk (strcat "multileader style " name " (annotative " (if anno "yes" "no") ")")
             (= (asg:dv e 296 0) (if anno 1 0)))
    (asg:chk (strcat "multileader style " name " - MISSING") nil)))

(defun asg:tblstyle (name / d)
  (setq d (cdr (assoc -1 (dictsearch (namedobjdict) "ACAD_TABLESTYLE"))))
  (asg:chk (strcat "table style " name) (and d (dictsearch d name))))

(defun asg:scales (want / names)
  (foreach p (dictsearch (namedobjdict) "ACAD_SCALELIST")
    (if (= (car p) 350) (setq names (cons (cdr (assoc 300 (entget (cdr p)))) names))))
  (foreach s want (asg:chk (strcat "annotation scale " s) (member s names)))
  (asg:chk (strcat "annotation scale list: " (itoa (length names)) " entries, no duplicates")
           (= (length names) (length (asg:uniq names)))))

(defun asg:get (fn obj / r) (setq r (vl-catch-all-apply fn (list obj))) (if (asg:ok r) r nil))
(defun asg:list (fn obj / r)
  (setq r (vl-catch-all-apply '(lambda () (vlax-safearray->list (vlax-variant-value (apply fn (list obj)))))))
  (if (asg:ok r) r nil))

(defun asg:layout (name media ctb / lay names num den std)
  (if (setq lay (asg:item (vla-get-Layouts (asg:doc)) name))
    (progn
      (vl-catch-all-apply 'vla-RefreshPlotDeviceInfo (list lay))
      (asg:chk (strcat name ": plot device DWG To PDF.pc3")
               (asg:same (asg:get 'vla-get-ConfigName lay) "DWG To PDF.pc3"))
      (setq names (asg:list 'vla-GetCanonicalMediaNames lay))
      (asg:chk (strcat name ": paper " media " exists on device and is selected")
               (and (member media names) (asg:same (asg:get 'vla-get-CanonicalMediaName lay) media)))
      (asg:chk (strcat name ": plot area = Layout") (equal (asg:get 'vla-get-PlotType lay) 5))
      (vl-catch-all-apply 'vla-GetCustomScale (list lay 'num 'den))
      (setq std (and (equal (asg:get 'vla-get-UseStandardScale lay) :vlax-true)
                     (equal (asg:get 'vla-get-StandardScale lay) 16)))
      (asg:chk (strcat name ": plot scale 1:1")
               (or std (and (numberp num) (numberp den) (/= den 0) (equal (/ (float num) den) 1.0 1e-9))))
      (asg:chk (strcat name ": plot style table " ctb) (asg:same (asg:get 'vla-get-StyleSheet lay) ctb))
      (setq names (asg:list 'vla-GetPlotStyleTableNames lay))
      (asg:chk (strcat name ": " ctb " installed in Plot Styles folder")
               (vl-some '(lambda (x) (asg:same x ctb)) names))
      (asg:chk (strcat name ": plot object lineweights on, not scaled")
               (and (equal (asg:get 'vla-get-PlotWithLineweights lay) :vlax-true)
                    (equal (asg:get 'vla-get-ScaleLineweights lay) :vlax-false)))
      (asg:chk (strcat name ": viewport borders not plotted")
               (equal (asg:get 'vla-get-PlotViewportBorders lay) :vlax-false)))
    (asg:missing (strcat "layout " name))))

(defun asg:tbattrs (blk tags / e found)
  (if (setq e (tblobjname "BLOCK" blk))
    (progn
      (while (setq e (entnext e))
        (if (= (cdr (assoc 0 (entget e))) "ATTDEF")
          (setq found (cons (strcase (cdr (assoc 2 (entget e)))) found))))
      (asg:chk (strcat "title block " blk ": " (itoa (length tags)) " attributes")
               (and (= (length found) (length tags))
                    (vl-every '(lambda (tg) (member tg found)) tags))))
    (asg:missing (strcat "title block " blk))))

(defun asg:noxrefs (/ b ok)
  (setq ok T b (tblnext "BLOCK" T))
  (while b
    (if (= 4 (logand 4 (cdr (assoc 70 b)))) (setq ok nil))
    (setq b (tblnext "BLOCK")))
  (asg:chk "no external references" ok))

(defun asg:writelog (/ fn f)
  (setq fn (strcat (getvar "DWGPREFIX") "ASG_QA_Log.txt")
        f (vl-catch-all-apply 'open (list fn "w")))
  (if (and f (asg:ok f))
    (progn
      (if asg:wlines
        (progn
          (write-line (strcat "ASG-SETUP warnings: " (itoa (length asg:wlines))) f)
          (foreach l (reverse asg:wlines) (write-line l f))
          (write-line "" f)))
      (foreach l (reverse asg:lines) (write-line l f))
      (close f)
      (princ (strcat "\nQA log written: " fn)))
    (princ "\nQA log could not be written (folder read-only).")))
'''

LISP_TAIL = r'''
;; ------------------------------------------------------------ setup steps
(defun asg:setup-steps (/ r)
  (foreach step '(("Table styles" . asg:tablestyles) ("Page setups" . asg:pagesetups)
                  ("Drawing variables" . asg:setvars))
    (princ (strcat "\n" (car step) ":"))
    (setq r (vl-catch-all-apply (cdr step) nil))
    (if (vl-catch-all-error-p r) (asg:warnmsg (car step) r))))

(defun c:ASG-SETUP ()
  (setq asg:warn 0 asg:wlines nil)
  (princ "\nASG-SETUP ---------------------------------------------")
  (asg:setup-steps)
  (c:ASG-QA)
  (princ (strcat "\nASG-SETUP complete with " (itoa asg:warn) " warning(s)."))
  (princ))

;; -------------------------------------------------------------- installer
(defun asg:files () (vla-get-Files (vla-get-Preferences (vlax-get-acad-object))))
(defun asg:first-path (p / i) (if (and p (setq i (vl-string-search ";" p))) (substr p 1 i) p))
(defun asg:slash (p) (if (and p (/= p "") (/= (substr p (strlen p)) "\\")) (strcat p "\\") p))
(defun asg:pref (fn / r) (setq r (vl-catch-all-apply fn (list (asg:files)))) (if (asg:ok r) r nil))

(defun asg:copy (src dst)
  ;; overwrite copy, T on success
  (cond ((not (and src dst (findfile src))) nil)
        ((= (strcase src) (strcase dst)) T)
        (T (if (findfile dst) (vl-file-delete dst))
           (if (vl-file-copy src dst) T nil))))

(defun asg:saveas (path sym fallback / typ r)
  (setq typ (if (and (boundp sym) (numberp (eval sym))) (eval sym) fallback)
        r (vl-catch-all-apply 'vla-SaveAs (list (asg:doc) path typ)))
  (if (asg:ok r) T (progn (asg:warnmsg (strcat "save " path) r) nil)))

(setq asg:todo nil)
(defun asg:step (n total msg ok fix)
  (princ (strcat "\n  [" (itoa n) "/" (itoa total) "] " msg (if ok "  ...  OK" "  ...  NOT DONE")))
  (if (not ok)
    (progn
      (setq asg:todo (cons (strcat "- " msg ":\n   " fix) asg:todo))
      (princ (strcat "\n        Do it by hand: " fix))))
  ok)

(defun asg:find (dir names / f)
  (vl-some '(lambda (n) (if (setq f (findfile (strcat dir n))) f)) names))

(defun asg:done-box (title lines)
  (princ (strcat "\n" title))
  (foreach l lines (princ (strcat "\n" l)))
  (alert (strcat title "\n\n" (apply 'strcat (mapcar '(lambda (l) (strcat l "\n")) lines)))))

;; CAD in-charge: ASG_Master_Template.dxf is open
(defun asg:install-master (/ files pkg ctb-src ctb-dir tpl-dir dwt kit n)
  (setq files (asg:files) pkg (getvar "DWGPREFIX") n 7
        ctb-src (asg:find pkg '("ASG_Monochrome.ctb" "..\\04_Plotting_Standards\\ASG_Monochrome.ctb"
                                "..\\09_Team_Kit\\ASG_Monochrome.ctb"))
        ctb-dir (asg:slash (asg:first-path (asg:pref 'vla-get-PrinterStyleSheetPath)))
        tpl-dir (asg:slash (asg:pref 'vla-get-TemplateDwgPath))
        dwt (if tpl-dir (strcat tpl-dir "ASG_Master_Template.dwt"))
        kit (strcat pkg "..\\09_Team_Kit\\"))
  (princ "\n\nASG INSTALL - building the company template ------------------")
  (asg:step 1 n "Install print setting ASG_Monochrome.ctb"
            (and ctb-dir (asg:copy ctb-src (strcat ctb-dir "ASG_Monochrome.ctb")))
            (strcat "copy 04_Plotting_Standards\\ASG_Monochrome.ctb into " (if ctb-dir ctb-dir "the Plot Styles folder (STYLESMANAGER)")))
  (asg:setup-steps)
  (asg:step 2 n "Create table styles, page setups and drawing settings" (= asg:warn 0)
            "send ASG_QA_Log.txt to the CAD in-charge (WARN lines)")
  (c:ASG-QA)
  (asg:step 3 n (strcat "Quality check: " (itoa asg:pass) " PASS, " (itoa asg:fail) " FAIL") (= asg:fail 0)
            "send ASG_QA_Log.txt (in the template folder) to the CAD in-charge")
  (asg:step 4 n (strcat "Save template " (if dwt dwt "ASG_Master_Template.dwt"))
            (and dwt (asg:saveas dwt 'ac2018_Template 66))
            "SAVEAS > AutoCAD Drawing Template (*.dwt) > name ASG_Master_Template")
  (asg:step 5 n "Save master copy ASG_Master_Template.dwg"
            (asg:saveas (strcat pkg "ASG_Master_Template.dwg") 'ac2018_dwg 64)
            "SAVEAS > AutoCAD 2018 Drawing (*.dwg) in 01_Master_Template")
  (asg:step 6 n "Put the template into the Team Kit folder (09_Team_Kit)"
            (and dwt (vl-file-directory-p kit) (asg:copy dwt (strcat kit "ASG_Master_Template.dwt")))
            (strcat "copy " (if dwt dwt "the DWT") " into 09_Team_Kit"))
  (asg:step 7 n "Make it the default for new drawings (Ctrl+N)"
            (and dwt (asg:ok (vl-catch-all-apply 'vla-put-QNewTemplateFile (list files dwt))))
            "OPTIONS > Files > Template Settings > Default Template File Name for QNEW")
  (asg:done-box
    (if asg:todo "ASG INSTALL FINISHED - SOME ITEMS NEED YOU" "ASG INSTALL COMPLETE")
    (append
      (if asg:todo (cons "Please do these by hand:" (reverse asg:todo)))
      (list ""
            "NEXT:"
            "1. Close this drawing."
            "2. Press Ctrl+N - every new drawing now starts from the ASG template."
            "3. To set up your team: zip the folder 09_Team_Kit and send it."
            "   Each person drags ASG_Install.lsp into AutoCAD - done."))))

;; Team member: install the template from the Team Kit
(defun asg:install-team (/ files src dir ctb-dir tpl-dir dwt n)
  (setq files (asg:files) n 3
        ctb-dir (asg:slash (asg:first-path (asg:pref 'vla-get-PrinterStyleSheetPath)))
        tpl-dir (asg:slash (asg:pref 'vla-get-TemplateDwgPath)))
  (princ "\n\nASG INSTALL - installing the company template on this PC -----")
  (setq src (getfiled "ASG Install: select ASG_Master_Template.dwt in the ASG Team Kit folder" "" "dwt" 0))
  (if (not src)
    (asg:done-box "ASG INSTALL CANCELLED"
                  (list "No template selected. Drag ASG_Install.lsp into AutoCAD again"
                        "and select ASG_Master_Template.dwt from the Team Kit folder."))
    (progn
      (setq dir (asg:slash (vl-filename-directory src))
            dwt (if tpl-dir (strcat tpl-dir "ASG_Master_Template.dwt")))
      (asg:step 1 n "Install the template ASG_Master_Template.dwt"
                (and dwt (asg:copy src dwt))
                (strcat "copy ASG_Master_Template.dwt into " (if tpl-dir tpl-dir "the Template folder")))
      (asg:step 2 n "Install print setting ASG_Monochrome.ctb"
                (and ctb-dir (asg:copy (strcat dir "ASG_Monochrome.ctb") (strcat ctb-dir "ASG_Monochrome.ctb")))
                (strcat "copy ASG_Monochrome.ctb into " (if ctb-dir ctb-dir "the Plot Styles folder (STYLESMANAGER)")))
      (asg:step 3 n "Make it the default for new drawings (Ctrl+N)"
                (and dwt (findfile dwt) (asg:ok (vl-catch-all-apply 'vla-put-QNewTemplateFile (list files dwt))))
                "OPTIONS > Files > Template Settings > Default Template File Name for QNEW")
      (asg:done-box
        (if asg:todo "ASG INSTALL FINISHED - SOME ITEMS NEED YOU" "ASG INSTALL COMPLETE")
        (append
          (if asg:todo (cons "Please do these by hand:" (reverse asg:todo)))
          (list ""
                "NEXT: press Ctrl+N. Every new drawing now starts from the ASG template."
                "Keep ASG_CAD_Quick_SOP.pdf at your desk."))))))

(defun c:ASG-INSTALL (/ r)
  (setq asg:todo nil asg:warn 0 asg:wlines nil)
  (setq r (vl-catch-all-apply
            (if (wcmatch (strcase (getvar "DWGNAME")) "ASG_MASTER_TEMPLATE.DXF")
              'asg:install-master
              'asg:install-team)
            nil))
  (if (vl-catch-all-error-p r)
    (alert (strcat "ASG INSTALL stopped unexpectedly:\n" (vl-catch-all-error-message r)
                   "\n\nPlease send a screenshot of the command line (F2) to the CAD in-charge.")))
  (princ))

(princ "\nASG_Install loaded - running installer. Commands: ASG-INSTALL, ASG-SETUP, ASG-QA, ASG-PROFILE.")
(c:ASG-INSTALL)
(princ)
'''


def build_lisp():
    L = [LISP_HEAD.replace("{rev}", S.STANDARD_REV)]
    # table styles
    L.append("(defun asg:tablestyles ()")
    for name, t, h, d, ts, hs, use in S.TABLE_STYLES:
        L.append(f"  (asg:ts {_s(name)} {_s(use)} {t[0]} {S.TABLE_ALIGN_CODE[t[1]]} "
                 f"{h[0]} {S.TABLE_ALIGN_CODE[h[1]]} {d[0]} {S.TABLE_ALIGN_CODE[d[1]]} {_b(ts)} {_b(hs)})")
    L.append("  (princ))\n")
    # drawing variables
    L.append("(defun asg:setvars (/ r)")
    L.append("  (foreach p '(" + " ".join(f"({_s(v)} . {_atom(x)})" for v, x, _p in S.SETUP_DRAWING_VARS) + ")")
    L.append("    (setq r (vl-catch-all-apply 'setvar (list (car p) (cdr p))))")
    L.append('    (princ (strcat "\\n  " (car p) (if (vl-catch-all-error-p r) " NOT SET (not supported in this release)" " set"))))')
    L.append("  (princ))\n")
    # QA
    L.append("(defun asg:qa-body ()")
    L.append(f'  (asg:out "ASG-QA  -  ASG CAD Master Standard {S.STANDARD_REV}  -  read-only check")')
    L.append('  (asg:out (strcat "Drawing: " (getvar "DWGPREFIX") (getvar "DWGNAME")))')
    L.append('  (if (not (asg:master)) (asg:out "NOTE  Not the master template: ASG-QA checks TEMPLATE settings. '
             'In a project drawing FAIL on current layer / style / scale / model space is normal."))')
    L.append("  ;; units and drawing variables")
    for var, val, _p in S.HEADER_VARS:
        if isinstance(val, tuple) or var in ("$UCSXDIR", "$UCSYDIR", "$UCSORG"):
            continue
        if var == "$CECOLOR":  # getvar returns a string for CECOLOR
            val = {256: "BYLAYER", 0: "BYBLOCK"}[val]
        L.append(f"  (asg:var {_s(var[1:])} {_atom(val)})")
    for var, val, _p in S.HEADER_STYLE_VARS:
        L.append(f"  (asg:var {_s(var[1:])} {_atom(val)})")
    for var, val, _p in S.SETUP_DRAWING_VARS:
        L.append(f"  (asg:var {_s(var)} {_atom(val)})")
    dv = S.dim_values("ASG-DIM-ANNO")
    L.append("  ;; current dimension variables = ASG-DIM-ANNO (no style overrides)")
    for k in ("dimtxsty", "dimtxt", "dimasz", "dimdec", "dimexo", "dimexe", "dimgap", "dimtad", "dimlfac"):
        L.append(f"  (asg:var {_s(k.upper())} {_atom(dv[k])})")
    L.append("  ;; linetypes")
    for name in S.LINETYPES:
        L.append(f'  (asg:chk "linetype {name} loaded" (tblsearch "LTYPE" {_s(name)}))')
    L.append("  ;; layers: colour, linetype, lineweight, plot flag")
    for _c, name, _g, aci, lt, lw, plot, _d, _u in S.LAYERS:
        L.append(f"  (asg:layer {_s(name)} {aci} {_s(lt)} {int(round(lw * 100))} {int(plot)})")
    L.append("  ;; styles")
    for name, ttf, _b2, anno, _u in S.TEXT_STYLES:
        L.append(f"  (asg:tstyle {_s(name)} {_s(ttf)} {_b(anno)})")
    for name, anno, over, _u in S.DIM_STYLES:
        v = dict(S.DIM_BASE, **over)
        L.append(f"  (asg:dstyle {_s(name)} {v['dimdec']} {v['dimadec']} {_b(anno)})")
    for name, anno, *_r in S.MLEADER_STYLES:
        L.append(f"  (asg:mlstyle {_s(name)} {_b(anno)})")
    for name, *_r in S.TABLE_STYLES:
        L.append(f"  (asg:tblstyle {_s(name)})")
    L.append('  (asg:chk "multiline style ASG-MLINE-2" (dictsearch (cdr (assoc -1 (dictsearch (namedobjdict) "ACAD_MLINESTYLE"))) "ASG-MLINE-2"))')
    L.append("  (asg:scales '(" + " ".join(_s(f"1:{s}") for s in S.ANNO_SCALES) + "))")
    L.append("  ;; layouts and page setups")
    for name, w, h, paper, tb, vps in S.SHEETS:
        L.append(f"  (asg:layout {_s(name)} {_s(S.media_name(paper, w, h))} {_s(S.CTB_NAME)})")
        L.append(f'  (if (asg:item (vla-get-Layouts (asg:doc)) "{name}") '
                 f'(asg:chk "named page setup ASG-{name}" (asg:item (vla-get-PlotConfigurations (asg:doc)) "ASG-{name}")))')
    L.append("  ;; title blocks")
    tags = " ".join(_s(t) for t, *_r in S.TB_ATTRIBUTES)
    for tb in S.TB_SPECS:
        L.append(f"  (asg:tbattrs {_s(tb)} '({tags}))")
    L.append("  ;; content")
    L.append('  (asg:chk "model space is empty" (null (ssget "_X" (list (cons 410 "Model")))))')
    L.append("  (asg:noxrefs)")
    L.append("  T)\n")
    L.append("(defun c:ASG-QA (/ r)")
    L.append("  (setq asg:pass 0 asg:fail 0 asg:lines nil)")
    L.append("  (setq r (vl-catch-all-apply 'asg:qa-body nil))")
    L.append('  (if (vl-catch-all-error-p r) (asg:chk (strcat "QA stopped early: " (vl-catch-all-error-message r)) nil))')
    L.append('  (asg:out (strcat "RESULT: " (itoa asg:pass) " PASS, " (itoa asg:fail) " FAIL"))')
    L.append("  (asg:writelog)")
    L.append("  (princ))\n")
    # profile (opt-in)
    L.append("(defun c:ASG-PROFILE (/ r)")
    L.append('  (initget "Yes No")')
    L.append('  (if (= (getkword "\\nChange YOUR AutoCAD profile (registry) settings to ASG defaults? [Yes/No] <No>: ") "Yes")')
    L.append("    (progn")
    L.append("      (foreach p '(" + " ".join(f"({_s(v)} . {_atom(x)})" for v, x, _p in S.PROFILE_VARS) + ")")
    L.append("        (setq r (vl-catch-all-apply 'setvar (list (car p) (cdr p))))")
    L.append('        (princ (strcat "\\n  " (car p) (if (vl-catch-all-error-p r) " not set" " set"))))')
    L.append('      (princ "\\nASG profile settings applied."))')
    L.append('    (princ "\\nNo changes made."))')
    L.append("  (princ))")
    L.append(LISP_TAIL)
    text = "\n".join(L)
    _check_parens(text)
    SETUP_LSP.parent.mkdir(parents=True, exist_ok=True)
    SETUP_LSP.write_text(text.replace("\n", "\r\n"), encoding="ascii")


def _check_parens(text):
    """Structural check of the generated LISP: balanced parentheses outside
    strings and comments, every top-level form closed."""
    depth, in_str, esc, comment = 0, False, False, False
    for ch in text:
        if comment:
            comment = ch != "\n"
            continue
        if in_str:
            if esc:
                esc = False
            elif ch == "\\":
                esc = True
            elif ch == '"':
                in_str = False
            continue
        if ch == ";":
            comment = True
        elif ch == '"':
            in_str = True
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth < 0:
                raise ValueError("ASG_Install.lsp: unbalanced ')'")
    if depth or in_str:
        raise ValueError(f"ASG_Install.lsp: unbalanced, depth {depth}, open string {in_str}")


# ---------------------------------------------------------------------------
# Temporary QA drawing - SEPARATE from the master (never a template)
# ---------------------------------------------------------------------------
QA_LW_Y0 = 250.0  # paper y of first lineweight sample
QA_LW_STEP = 9.0
QA_LW_X = (135.0, 185.0)
QA_VIEWPORTS = (((25, 15, 125, 282), 20, (450, 1100)),
                ((130, 15, 225, 140), 5, (5120, 120)))


def build_qa_drawing():
    a3 = [s for s in S.SHEETS if s[0] == "A3-LANDSCAPE"]
    doc = S.new_document(sheets=a3)
    msp = doc.modelspace()
    # 1:20 test geometry - a 1200 x 2400 opening
    msp.add_lwpolyline([(0, 0), (1200, 0), (1200, 2400), (0, 2400)], close=True,
                       dxfattribs={"layer": "ASG-OUTLINE-PRIMARY"})
    for p1, p2, base, ang in (((0, 0), (1200, 0), (0, -300), 0), ((0, 0), (0, 2400), (-300, 0), 90)):
        msp.add_linear_dim(base=base, p1=p1, p2=p2, angle=ang, dimstyle="ASG-DIM-FIXED",
                           override={"dimscale": 20}, dxfattribs={"layer": "ASG-DIMENSION"}).render()
    t = msp.add_text("TEXT 2.5 @1:20", height=2.5 * 20,
                     dxfattribs={"style": "ASG-TEXT-NOTE", "layer": "ASG-TEXT-NOTE"})
    t.set_placement((0, 2550))
    # 1:5 detail geometry at x = 5000
    ox = 5000
    sq = [(ox, 0), (ox + 50, 0), (ox + 50, 100), (ox, 100)]
    msp.add_lwpolyline(sq, close=True, dxfattribs={"layer": "ASG-SECTION-CUT"})
    hatch = msp.add_hatch(dxfattribs={"layer": "ASG-HATCH-FILL"})
    hatch.set_solid_fill(color=256)
    hatch.paths.add_polyline_path(sq, is_closed=True)
    msp.add_linear_dim(base=(ox, -25), p1=(ox, 0), p2=(ox + 50, 0), dimstyle="ASG-DIM-DETAIL",
                       override={"dimscale": 5}, dxfattribs={"layer": "ASG-DIMENSION"}).render()
    c = Vec2(ox + 150, 0)
    msp.add_line(c, c + Vec2(120, 0), dxfattribs={"layer": "ASG-OUTLINE-SECONDARY"})
    msp.add_line(c, c + Vec2.from_deg_angle(30, 120), dxfattribs={"layer": "ASG-OUTLINE-SECONDARY"})
    msp.add_angular_dim_cra(center=c, radius=90, start_angle=0, end_angle=30, distance=0,
                            dimstyle="ASG-DIM-ANGULAR", override={"dimscale": 5},
                            dxfattribs={"layer": "ASG-DIMENSION"}).render()
    cc = (ox + 100, 200)
    msp.add_circle(cc, 40, dxfattribs={"layer": "ASG-OUTLINE-SECONDARY"})
    msp.add_radius_dim(center=cc, radius=40, angle=45, dimstyle="ASG-DIM-RADIUS",
                       override={"dimscale": 5}, dxfattribs={"layer": "ASG-DIMENSION"}).render()
    msp.add_diameter_dim(center=cc, radius=40, angle=200, dimstyle="ASG-DIM-DIAMETER",
                         override={"dimscale": 5}, dxfattribs={"layer": "ASG-DIMENSION"}).render()
    # objects that must NOT appear on a plot
    msp.add_line((0, 0), (1200, 2400), dxfattribs={"layer": "ASG-CONSTRUCTION"})
    msp.add_text("NOPLOT", height=100, dxfattribs={"layer": "ASG-NOPLOT"}).set_placement((300, 1200))

    lay = doc.layouts.get("A3-LANDSCAPE")
    for e in list(lay):
        if e.dxftype() == "VIEWPORT" and e.dxf.id != 1:
            lay.delete_entity(e)
    for (x1, y1, x2, y2), scale, ctr in QA_VIEWPORTS:
        vp = lay.add_viewport(center=((x1 + x2) / 2, (y1 + y2) / 2), size=(x2 - x1, y2 - y1),
                              view_center_point=ctr, view_height=(y2 - y1) * scale,
                              dxfattribs={"layer": "ASG-VIEWPORT"})
        vp.dxf.flags |= 16384
    x1, x2 = QA_LW_X
    for i, (lw, cls, _u) in enumerate(S.LW_MATRIX):
        y = QA_LW_Y0 - i * QA_LW_STEP
        layer = next(l[1] for l in S.LAYERS if l[5] == lw and l[6])
        lay.add_line((x1, y), (x2, y), dxfattribs={"layer": layer})
        S._text(lay, f"{lw:.2f} {cls} - {layer}", x2 + 3, y - 1, 1.8, "ASG-TEXT-SHEET", "ASG-TEXT")
    y = 200
    for use, h, style in S.TEXT_HEIGHTS:
        y -= h + 2.5
        S._text(lay, f"{h} mm {use}", 135, y, h, style.split(" ")[0], "ASG-TEXT")
    S.save_dxf(doc, QA_DXF)


def main():
    build_master()
    build_size_templates()
    build_page_setup_register()
    build_ctb()
    build_lisp()
    build_qa_drawing()
    for p in sorted(ROOT.rglob("*")):
        if p.is_file() and p.suffix in (".dxf", ".ctb", ".csv", ".lsp"):
            print("written", p.relative_to(ROOT))


if __name__ == "__main__":
    main()
